### ISSUE TITLE
Cannot create VCF instance when no sample data (but FORMAT defined)

### ISSUE THREAD

**Issue by bommox** [GMOD/vcf-js#72]
Sometimes there are VCFs with annotation data and no sample info.

So the available columns are:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
```

For instance:
https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/1000G_phase1.snps.high_confidence.b37.vcf.gz

When creating the instance, it complains with this error:

```
(node:22148) UnhandledPromiseRejectionWarning: Error: VCF header has FORMAT but no samples:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
    at C:\Users\1\adntro\repos\bionos-research\node_modules\@gmod\vcf\dist\parse.js:63:17
```

```
const REMOTE_URL = 'https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/1000G_phase1.snps.high_confidence.b37.vcf.gz';
const remoteIndexed = new TabixIndexedFile({
  filehandle: new RemoteFile(REMOTE_URL, {fetch}),
  tbiFilehandle: new RemoteFile(REMOTE_URL + '.tbi', {fetch}),
  //renameRefSeqs: refSeq => refSeq.replace('chr','')
});
```

NOTE that it works with other VCFs with no sample data, such as: https://storage.googleapis.com/gcp-public-data--broad-references/hg19/v0/dbsnp_138.b37.vcf.gz

It would be great to be able to parse this kind of VCF files to perform queries about annotations (gene, population frequencies, etc.)

Regards!

**Comment by cmdcolin** [comment]
I think this may be due to extra whitespace being stored after the INFO column in the header line on that file...this confuses our parser into thinking it has a FORMAT column since we say headerline.split('\t') and count the number of columns. We could try to be more robust to this particular issue by actually checking that it says FORMAT or filtering out whitespace!

**Comment by bommox** [comment]
Hi, I understand. As I am trying with some public datasets it would be nice to make it work.

Do you think it's an easy fix? or want me to contribute via pull-request?

Regards :)

**Comment by bommox** [comment]
Thanks @cmdcolin ! 
You are doing great job with this JS libraries!
