### ISSUE TITLE
Memory leak in lazy-handling of property SAMPLES

### ISSUE THREAD

**Issue by bpow** [GMOD/vcf-js#85]
Well, "memory leak" vs. "keeping things in memory when no longer needed"-- pretty much the same thing...

Laziness of the SAMPLES property is handled by having a Variant object re-defined in each run through the `parseLine` function, then defining a property on the proto of this new object definition which ends up being a closure to calculate the SAMPLES object if requested.

From what I can tell, though, it looks like when the value is calculated, it is applied to the variant object itself, and the closure remains in the SAMPLES property on the __proto__ of the variant, so the captured variables in the lexical scope of the closure hang around as long as the object does (instead of being eligible for GC after the SAMPLES value is calculated).

In chrome, at least (where I can figure out how to see what the closure captures), it looks like this results in `fields`, `info` and `rest` remaining around.

Proposed change: define the temporary getter on the object itself instead of the proto (making it `configurable: true`), then replace the property with a value property later on when the value is calculated.

**Comment by bpow** [comment]
In some quick testing of the code in PR #86, I get the following results when loading ~127k variants in nodejs and keeping them in memory (mileage is of course expected to vary with different javascript runtimes...):

|             | run time (s) | heapUsed (MB) | max RSS (MB) |
| --------- | --------------- | ---------------------- | ------------ |
| upstream - not accessed | 4.85 | 261.42 | 330.93 |
| upstream - accessed | 11.91 | 428.86 | 516.83 |
| changed - not accessed | 2.45 | 148.54 | 208.43 |
| changed - accessed | 8.43 | 259.51 | 362.29 |

"Upstream is current" tip the gmod/vcf-js repository, "changed" is #86 . "Not accessed" is when variant.SAMPLES is not called, "accessed" is when it is (I just called it and kept track of the sum of samples to make sure that access didn't get optimized away).

Runtime and max RSS were measured with `/usr/bin/time -v` and `heapUsed` was measured as `process.memoryUsage().heapUsed / 1024 / 1024`.

So it looks (at least in nodejs) as a win overall both in terms of time and space usage (whether the lazy property is called or not). I suspect some of the benefit is being able to GC after the closure has been called, but the uniformity of `__proto__`s may also help the v8 engine optimize objects (and their "hidden classes") better.

**Comment by cmdcolin** [comment]
nice catch! I had wanted at one point to try to make the Variant a normal es6 class but it was tricky...we can check out the PR you made

**Comment by bpow** [comment]
It might make more sense for Variant to be a normal es6 class somehow-- as it is in the PR, it has really just turned into something for "tagging" and it could be an anonymous object since the prototype isn't used in that method-- I kept it in because without it all of the jest snapshot-based tests fail (because the Variants become plain-old Objects)

**Comment by cmdcolin** [comment]
fixed by #86 ! and indeed, it is nice to keep 100% snapshot working. becoming plain old objects is ok but the main thing that was hard for me with the ES6 classes was that I wanted to add e.g. a private class property pointing to the parse (e.g. the handle for that=this in the current code) but currently users of this class expect that they can JSON.stringify(variant) and it just contains stuff they are interested in, but if i add the extra properties, it doesn't stringify nicely
