### ISSUE TITLE
parse breakends in ALT field

### ISSUE THREAD

**Issue by rbuels** [GMOD/vcf-js#9]
keep the ALT in the returned JSON unchanged for backcompat.

add a PARSED_ALT or similar attribute that parses the ALT further if it is a breakend expression (e.g. `G]2:421681]`)

If the alt parsing is intensive, might make PARSED_ALT lazily evaluated.

**Comment by rbuels** [comment]
This is for the standard VCF breakends in the spec, not the gnomad extensions.

**Comment by rbuels** [comment]
VCF spec: https://samtools.github.io/hts-specs/VCFv4.3.pdf

**Comment by ihh** [comment]
The Samtools BND syntax for breakends in VCF is what I used for the [Rotunda demo](http://jbrowse.org/itcr/rotunda/). And more importantly, I believe it is indeed the standard.

**Comment by cmdcolin** [comment]
small tidbit where manta indicates stuff about breakend graph using variants ID https://github.com/Illumina/manta/blob/master/docs/developerGuide/ID.md
